#!/bin/bash
# install cli2 for cloud9 environment
echo "installing"
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
/usr/local/bin/aws --version
sudo ln -s /usr/local/aws-cli/v2/current/bin/aws /usr/bin/aws